# Generated by Django 3.2.6 on 2022-01-06 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20220106_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time_tobe_completed',
            field=models.DateField(),
        ),
    ]
